server:
    port: 8081

spring:
    application:
        name: user-service

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/myapp-realm
                    jwk-set-uri: http://localhost:8080/realms/myapp-realm/protocol/openid-connect/certs

    datasource:
        url: jdbc:postgresql://localhost:5432/userdb
        username: postgres
        password: "0000"
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: false
        locations: classpath:db/migration
        baseline-on-migrate: false
        clean-disabled: true
        validate-on-migrate: true

    data:
        redis:
            host: localhost
            port: 6379
            password: "0000"
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: false
        consumer:
            group-id: user-service-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "com.microservice.userservice.messaging.event"
keycloak:
    server-url: http://localhost:8080
    realm: myapp-realm
    client-id: user-service
    client-secret: user-service-secret-change-in-prod

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
