server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentorship_db
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapp-realm
          jwk-set-uri: http://localhost:8080/realms/myapp-realm/protocol/openid-connect/certs

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  email:
    from: ${APP_EMAIL_FROM:no-reply@pi-clouddoom.local}


gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}

openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
  model: ${OPENAI_MODEL:gpt-4o-mini}

