apiVersion: v1
kind: ResourceQuota
metadata:
  name: piclouddoom-quota
  namespace: piclouddoom
spec:
  hard:
    pods: "40"
    requests.cpu: "8"
    requests.memory: 12Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
